
/* Drop Tables */
/*
DROP TABLE SCRAP CASCADE CONSTRAINTS;
DROP TABLE SALES CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
*/



/* Create Tables */

CREATE TABLE CAR
(
	CAR_NO number NOT NULL,
	CAR_NAME nvarchar2(50) NOT NULL,
	CAR_YEAR number(4) DEFAULT 2021,
	PRIMARY KEY (CAR_NO)
);


CREATE TABLE Customer
(
	ID varchar2(10) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	TEL varchar2(20),
	ADDR nvarchar2(50),
	REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (ID)
);


CREATE TABLE SALES
(
	SALES_NO number NOT NULL,
	ID varchar2(10) NOT NULL,
	CAR_NO number NOT NULL,
	SALES_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (SALES_NO)
);


CREATE TABLE SCRAP
(
	SALES_NO number NOT NULL,
	SCRAP_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (SALES_NO)
);



/* Create Foreign Keys */

ALTER TABLE SALES
	ADD FOREIGN KEY (CAR_NO)
	REFERENCES CAR (CAR_NO)
;


ALTER TABLE SALES
	ADD FOREIGN KEY (ID)
	REFERENCES Customer (ID)
;


ALTER TABLE SCRAP
	ADD FOREIGN KEY (SALES_NO)
	REFERENCES SALES (SALES_NO)
;

CREATE SEQUENCE SEQ_CAR
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_SALES
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_SCRAP
NOCACHE
NOCYCLE;



